### ISSUE TITLE
Logout session not working

### ISSUE THREAD

**Issue by bmuhamood** [balerum03/associations#1]
Logout session not working. We have tried all the routes and controllers and still getting some logical errors

**Comment by pastorp3** [comment]
controller session:
``
 def destroy
    session.destroy
    redirect_to root_path
  end
``

routes: 
``
 delete 'logout', to: 'sessions#destroy', as: 'logout'
``
app layout: 
``
<%= link_to 'Log Out', logout_path, method: :delete %>
``

**Comment by balerum03** [comment]
Thanks for the good advice, everything is working perfect now.
